version: '2'
services:
    employees-app:
        image: employees
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://employees-mysql:3306/employees?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    employees-mysql:
        extends:
            file: mysql.yml
            service: employees-mysql
